version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    command:
      - '--logpath'
      - '/dev/null'
  fastapi-server:
    build:
      context: ../
      dockerfile: docker/pytest.Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./cov:/code/cov/
    depends_on:
      - mongo
    environment:
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - TESTING=1
      - MONGO_URL=mongodb://mongo:27017
      - TEST_MONGO_URL=mongodb://mongo:27017
